### ISSUE TITLE
Github release tags

### ISSUE THREAD

**Issue by 0323pin** [cheukyin699/superdiff#2]
Hi,

I've just packaged and merged `superdiff` for NetBSD, [commit message](http://mail-index.netbsd.org/pkgsrc-changes/2022/12/29/msg266073.html).

Would you mind providing github release tags in sync with the releases in crates.io?
It makes it easier to monitor new releases and keep the package up-to-date. TIA.

**Comment by chuck-sys** [comment]
When you say github release tags, do you mean using the github release system to create releases based on current git version tags?

**Comment by 0323pin** [comment]
@cheukyin699 I could swear they weren't available earlier today. [This](https://github.com/cheukyin699/superdiff/tags) is exactly what I need. Thanks!
